# Generated by Django 3.1.3 on 2022-08-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matter.semester', verbose_name='Semestre'),
        ),
    ]
